env: DEVELOPMENT
db:
  username: ''
  password: ''
  database: ''
  host: ''
  port: 0
  dialect: sqlite # sqlite, mysql
  debug: true
secret: ''
grpc:
  host: ''
  port: 50051
http:
  host: ''
  port: 8000
  worker: 2
source: '/etc/mittens/automation_tasks'
