env: DEVELOPMENT
db:
  username: ''
  password: ''
  database: ''
  host: ''
  port: 0
  dialect: sqlite # sqlite, mysql
  debug: true
secret: 'a12345'
grpc:
  port: 50051
  worker: 10
http:
  host: ''
  port: 8000
  worker: 2
source: false
