# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofiles/report.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protofiles/report.proto\x12\rsrc.v1.report\"\x0f\n\rReportRequest\"=\n\x0eReportResponse\x12\x17\n\x0ftotal_testcases\x18\x01 \x01(\t\x12\x12\n\ntotal_tags\x18\x02 \x01(\t2Q\n\x06Report\x12G\n\x06Report\x12\x1c.src.v1.report.ReportRequest\x1a\x1d.src.v1.report.ReportResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofiles.report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTREQUEST']._serialized_start=42
  _globals['_REPORTREQUEST']._serialized_end=57
  _globals['_REPORTRESPONSE']._serialized_start=59
  _globals['_REPORTRESPONSE']._serialized_end=120
  _globals['_REPORT']._serialized_start=122
  _globals['_REPORT']._serialized_end=203
# @@protoc_insertion_point(module_scope)
