# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofiles/testcase.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protofiles/testcase.proto\x12\x0fsrc.v1.testcase\"J\n\nGetRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\r\x12\x0c\n\x04page\x18\x04 \x01(\r\"\x7f\n\x0bGetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12+\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1d.src.v1.testcase.DataResponse\x12\x33\n\x08metadata\x18\x03 \x01(\x0b\x32!.src.v1.testcase.MetaDataResponse\"\\\n\x10MetaDataResponse\x12\x14\n\x0c\x63urrent_page\x18\x01 \x01(\r\x12\x10\n\x08per_page\x18\x02 \x01(\r\x12\r\n\x05total\x18\x03 \x01(\r\x12\x11\n\tlast_page\x18\x04 \x01(\r\"\xa3\x01\n\x0c\x44\x61taResponse\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x03 \x01(\t\x12\"\n\x04tags\x18\x04 \x03(\x0b\x32\x14.src.v1.testcase.Tag\x12\x0f\n\x07\x63reator\x18\x05 \x01(\t\x12\x19\n\x11last_execute_date\x18\x06 \x01(\t\x12\x1b\n\x13last_execute_result\x18\x07 \x01(\t\"\"\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\"J\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\x12\x0f\n\x07tag_ids\x18\x04 \x03(\r\"1\n\x0e\x43reateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x18\n\nRunRequest\x12\n\n\x02id\x18\x01 \x01(\r\".\n\x0bRunResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdf\x01\n\x08Testcase\x12\x42\n\x03Get\x12\x1b.src.v1.testcase.GetRequest\x1a\x1c.src.v1.testcase.GetResponse\"\x00\x12K\n\x06\x43reate\x12\x1e.src.v1.testcase.CreateRequest\x1a\x1f.src.v1.testcase.CreateResponse\"\x00\x12\x42\n\x03Run\x12\x1b.src.v1.testcase.RunRequest\x1a\x1c.src.v1.testcase.RunResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofiles.testcase_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREQUEST']._serialized_start=46
  _globals['_GETREQUEST']._serialized_end=120
  _globals['_GETRESPONSE']._serialized_start=122
  _globals['_GETRESPONSE']._serialized_end=249
  _globals['_METADATARESPONSE']._serialized_start=251
  _globals['_METADATARESPONSE']._serialized_end=343
  _globals['_DATARESPONSE']._serialized_start=346
  _globals['_DATARESPONSE']._serialized_end=509
  _globals['_TAG']._serialized_start=511
  _globals['_TAG']._serialized_end=545
  _globals['_CREATEREQUEST']._serialized_start=547
  _globals['_CREATEREQUEST']._serialized_end=621
  _globals['_CREATERESPONSE']._serialized_start=623
  _globals['_CREATERESPONSE']._serialized_end=672
  _globals['_RUNREQUEST']._serialized_start=674
  _globals['_RUNREQUEST']._serialized_end=698
  _globals['_RUNRESPONSE']._serialized_start=700
  _globals['_RUNRESPONSE']._serialized_end=746
  _globals['_TESTCASE']._serialized_start=749
  _globals['_TESTCASE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
